export default[
	// Object.assign(
	{
		id: 0,
		lang: 'English',
		langCode: 'en',
		appName: 'TerriTool RE',
		signinTitle: 'Signin to Get Started!',
		email: 'Email Address',
		name: 'Name',
		password: 'Password',
		confirmPassword: 'Confirm Password',
		createAcc: 'Create Account',
		forgot: 'Forgot Your Password?',
		signin: 'Login',
		signup: 'Sign Up',
		reset: 'Reset',
		logout: 'Logout',

		home: 'Home',
		categories: 'Categories',
		settings: 'Settings',

		// App intro sliders
		slide1Title: 'SAMPLE TITLE 1',
		slide1Text: 'This is sample description 1',
		slide2Title: 'SAMPLE TITLE 2',
		slide2Text: 'This is sample description 2',
		slide3Title: 'SAMPLE TITLE 3',
		slide3Text: 'This is sample description 3',

		//Validation messages
		required: 'is required',
		notValid: 'is not valid',
		tooShort: 'Minimum {count, number} chars required',
		doesntMatch: 'doesn\'t match',

		featured: 'Featured',
		txtCredits: 'TXT Credits',
		liveCredits: 'Live Credits',
		text: 'Text',
		liveChat: 'Live Chat',
		psychicForYou: 'Psychic for you',
		messages: 'Messages',
		newsFeed: 'News Feed',
		readMore: 'Read More',
		dailyHoroscope: 'Daily Horoscope',
		today: 'Today',
		yesterday: 'Yesterday',
		tomorrow: 'Tomorrow',
		personalInformation: 'Personal Information',
		topUpMyBalance: 'Top up my Balance',
		textCredits: 'Text Credits',
		subscriptions: 'Subscriptions',
		youDoNotHaveEnoughTextCredits:'You do not have enough text credits',
		youDoNotHaveEnoughLiveCredits:'You do not have enough live credits',
		buy: 'Buy',
		support: 'Support',
		termsOfServices:'Terms of Services',
		crPerMin: 'Cr/Min',
		crPerMsg: 'Cr/Msg'
	},
	{
		id: 1,
		lang: 'Arabic',
		langCode: 'ar',
		appName: 'TerriTool RE',
		signinTitle: 'Signin to Get Started!',
		email: 'Email Address',
		name: 'Name',
		password: 'Password',
		confirmPassword: 'Confirm Password',
		createAcc: 'Create Account',
		forgot: 'Forgot Your Password?',
		signin: 'Login',
		signup: 'Sign Up',
		reset: 'Reset',
		logout: ' تسجيل خروج',

		home: 'Home',
		categories: 'Categories',
		settings: ' الاعدادات',

		// App intro sliders
		slide1Title: 'SAMPLE TITLE 1',
		slide1Text: 'This is sample description 1',
		slide2Title: 'SAMPLE TITLE 2',
		slide2Text: 'This is sample description 2',
		slide3Title: 'SAMPLE TITLE 3',
		slide3Text: 'This is sample description 3',

		//Validation messages
		required: 'is required',
		notValid: 'is not valid',
		tooShort: 'Minimum {count, number} chars required',
		doesntMatch: 'doesn\'t match',

		featured: ' متميز',
		txtCredits: ' رصيد',
		liveCredits: ' رصيد مباشر',
		text: ' رسالة',
		liveChat: ' دردشة',
		psychicForYou: ' عالم نفس',
		messages: ' رسائل',
		newsFeed: ' الأخبار',
		readMore: ' اقرأ أكثر',
		dailyHoroscope: ' الأبراج اليومية',
		today: ' اليوم',
		yesterday: ' البارحة',
		tomorrow: ' غدا',
		personalInformation: ' معلومات شخصية',
		topUpMyBalance: ' اشحن رصيدي',
		textCredits: ' رصيد رسائل',
		subscriptions: ' اشتراك',
		youDoNotHaveEnoughTextCredits:' ليس لديك رصيد كافي',
		youDoNotHaveEnoughLiveCredits:'ليس لديك ما يكفي من الاعتمادات الحية',
		buy: ' اشتري',
		support: ' دعم تقني',
		termsOfServices:' شروط الخدمة',
		crPerMin: 'الائتمان / الدقيقة',
		crPerMsg: 'الائتمان / الرسالة'
	}
	// )
];